### ISSUE TITLE
Ajustar Workflow de Integração Contínua para Execução Diária

### ISSUE THREAD

**Issue by thaleseuflauzino** [unb-mds/LicitaBSB-24.1#84]
**Descrição/Objetivo:**
Ajustar o workflow de integração contínua para que seja executado diariamente, garantindo que a integração e a validação do código sejam realizadas de forma contínua e regular.

**Tarefas:**
- [x] Analisar o workflow atual de integração contínua.
- [x] Ajustar a configuração do workflow para que seja executado diariamente.
- [x] Testar o novo workflow para garantir que está funcionando conforme esperado.
- [x] Documentar as mudanças realizadas no workflow.
- [x] Notificar a equipe sobre a atualização do workflow.

**Critérios de aceitação (opcional):**
- [x] O workflow de integração contínua é executado diariamente sem falhas.
- [x] As mudanças no workflow são documentadas e compreendidas pela equipe.
- [x] A equipe está ciente e concorda com a atualização do workflow.

**Contexto adicional:**
Atualmente, o workflow de integração contínua está configurado para ser executado a cada semana. A mudança para uma execução diária visa melhorar a regularidade e a eficácia do processo de integração contínua.

**Comment by thaleseuflauzino** [comment]
# Documentação de Alteração de Workflow

## Alteração do Workflow de Semanal para Diário

### Contexto

Esta documentação descreve a alteração realizada no workflow do projeto, onde a frequência de execução foi modificada de semanal para diária. Esta mudança foi implementada para garantir que os dados raspados estejam sempre atualizados.

### Detalhes da Alteração

#### 1. Workflow Original

O workflow original era configurado para executar semanalmente. A configuração do cronjob no GitHub Actions estava definida da seguinte forma:

```yaml
name: Script de automação da extração das Licitações de Brasília

on:
  workflow_dispatch:
  schedule:
    - cron: '00 01 * * SAT' # Executa semanalmente, todos os sábados às dez horas da noite.
```

#### 2. Workflow Atualizado
O workflow foi atualizado para ser executado diariamente. A nova configuração do cronjob é a seguinte:

```yaml
name: Script de automação da extração das Licitações de Brasília

on:
  workflow_dispatch:
  schedule:
    - cron: '01 03 * * *' # Executa diariamente, todos os dias à meia-noite (00h01)
```
### Script de Raspagem de Dados
O script de raspagem de dados utilizado permanece o mesmo. Ele está localizado no repositório e é executado automaticamente pelo GitHub Actions de acordo com a programação definida.

#### Configuração do GitHub Actions
Aqui está a configuração completa do arquivo de workflow (.github/workflows/main.yml):

```yaml
name: Script de automação da extração das Licitações de Brasília

on:
  workflow_dispatch:
  schedule:
    - cron: '01 03 * * *'

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run data_collection_avisos script
      run: |
        echo "Running data_collection_avisos script..."
        python3 backend/data_collection_avisos/main.py
        echo "Finished data_collection_avisos script."

    - name: Run data_collection_extrato script
      run: |
        echo "Running data_collection_extrato script..."
        python3 backend/data_collection_extrato/main.py
        echo "Finished data_collection_extrato script."


    - name: Commit and push updated last date
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@users.noreply.github.com"
        git pull origin main
        git add --all
        git commit -m "[CI] Licitações extraídas com sucesso!"
        git push
```
### Benefícios da Alteração
#### Atualização Constante dos Dados: Com a execução diária do script de raspagem, os dados estarão sempre atualizados.
#### Automatização: A configuração do cronjob no GitHub Actions automatiza totalmente o processo, eliminando a necessidade de execução manual.
#### Flexibilidade: A frequência de execução pode ser ajustada facilmente conforme a necessidade do projeto.
### Conclusão
A alteração do workflow de semanal para diário foi realizada com sucesso, utilizando um cronjob no GitHub Actions. Esta mudança garante que o processo de raspagem de dados seja executado diariamente, mantendo os dados atualizados e o processo automatizado.
